import assert from "node:assert/strict";
import { test } from "node:test";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { chromium } from "playwright";
import { appServer } from "./app-server.mjs";

test("review, context and composer remain usable at desktop and narrow widths", { timeout: 120000 }, async t => {
  const directory = await mkdtemp(join(tmpdir(), "citropy-harness-ui-"));
  const server = await appServer();
  const browser = await chromium.launch({ headless: true });
  t.after(async () => { await browser.close(); await server.close(); await rm(directory, { recursive: true, force: true }); });
  const page = await browser.newPage({ viewport: { width: 1440, height: 960 }, reducedMotion: "reduce" });
  page.setDefaultTimeout(20000);
  const errors = [];
  const calls = [];
  let revision = "review-1";
  page.on("pageerror", error => errors.push(error.message));
  const thread = { id: "chat", projectId: "project", provider: "claude", model: "example", title: "Review workspace changes", createdAt: 1, updatedAt: 1, running: false, status: "idle", permissionMode: "manual", checkpoints: [{ messageId: "prompt", before: "tree-before", after: "tree-after", createdAt: 1 }], usage: { input: 5000, output: 20, cacheRead: 0, cacheWrite: 0, costUsd: 0, contextTokens: 5000, contextMax: 200000, turns: 1 } };
  const project = { id: "project", name: "Product workspace", path: "/example", isGit: true, branch: "main", lastOpened: 1, settings: { workflows: [{ id: "review", name: "Review a file", prompt: "Review {{file}} and report concrete bugs.", parameters: [{ name: "file", default: "src/app.ts" }] }], actions: [{ id: "tests", name: "Unit tests", command: "npm test", trigger: "verify" }] } };
  const messages = [{ id: "prompt", role: "user", ts: 1, parts: [{ id: "user-text", kind: "text", text: "Improve the request handler." }] }, { id: "answer", role: "assistant", ts: 2, parts: [{ id: "reply", kind: "text", text: "The request handler now reports failures and retains the original response.", complete: true }] }];
  const patch = { path: "src/request.ts", added: 1, removed: 1, hunks: [{ header: "@@ -1,2 +1,2 @@", oldStart: 1, newStart: 1, lines: [{ type: "ctx", text: "export function request() {", oldNo: 1, newNo: 1 }, { type: "del", text: "  return null;", oldNo: 2 }, { type: "add", text: "  throw new Error('Request failed');", newNo: 2 }] }] };
  await page.addInitScript(() => { for (const [key, value] of Object.entries({ project: "project", thread: "chat", inspector: "0", theme: "dark", uiScale: "100" })) localStorage.setItem(`citropy.${key}`, value); });
  await page.routeWebSocket("**/socket*", socket => {
    socket.onMessage(raw => {
      const event = JSON.parse(raw);
      calls.push(event);
      if (event.t === "thread.load") socket.send(JSON.stringify({ t: "thread.messages", threadId: "chat", messages }));
      if (event.t === "thread.send") socket.send(JSON.stringify({ t: "thread.accepted", requestId: event.requestId }));
      if (event.t === "git.refresh") socket.send(JSON.stringify({ t: "git.status", projectId: "project", threadId: "chat", status: { branch: "main", clean: false, ahead: 0, behind: 0, upstream: "origin/main", files: [{ path: "src/request.ts", index: " ", worktree: "M", staged: false, added: 1, removed: 1 }] } }));
    });
    socket.send(JSON.stringify({ t: "hello", snapshot: { projects: [project], threads: [thread], home: "/example", providers: [{ id: "claude", label: "Claude Code", available: true, enabled: true, supportsPermissionPrompt: true, models: [{ id: "example", label: "Example model" }] }], permissions: [], assistance: { automaticTitles: true, commitModel: null, titleModel: null, reviewModel: null } } }));
  });
  await page.route("**/api/**", async route => {
    const url = new URL(route.request().url());
    const input = route.request().postData() ? route.request().postDataJSON() : undefined;
    calls.push({ path: url.pathname, input });
    if (["/api/skills", "/api/commands"].includes(url.pathname)) return route.fulfill({ json: [] });
    if (url.pathname === "/api/threads/review") return route.fulfill({ json: { scope: url.searchParams.get("scope"), patches: [patch], revision } });
    if (url.pathname === "/api/threads/hunk") { revision = "review-2"; return route.fulfill({ json: { ok: true } }); }
    if (url.pathname === "/api/threads/review-model") return route.fulfill({ json: { title: "Check the error path", body: "src/request.ts:2: callers must handle the rejected request.", revision } });
    if (url.pathname === "/api/threads/context") return route.fulfill({ json: route.request().method() === "GET" ? [{ path: "src/request.ts", dir: false }] : { references: [{ path: "src/request.ts", startLine: 1, endLine: 2 }], lastSources: [{ path: "src/request.ts", kind: "file", characters: 120 }], instructions: ["/example/AGENTS.md"], rebuilt: false } });
    return route.fulfill({ status: 404, json: { error: "Fixture route unavailable" } });
  });
  await page.goto(server.url);
  await page.getByText(messages[1].parts[0].text, { exact: true }).waitFor();
  await page.getByRole("button", { name: "Git actions", exact: true }).click();
  await page.getByRole("button", { name: "Review task changes", exact: true }).click();
  const review = page.getByRole("dialog", { name: "Review changes", exact: true });
  await review.getByText("src/request.ts", { exact: true }).waitFor();
  await review.getByRole("combobox", { name: "Review scope" }).selectOption("unstaged");
  await review.getByRole("button", { name: "Stage hunk", exact: true }).click();
  await page.waitForFunction(() => !document.querySelector('dialog[open] [aria-label="Refresh review"]').disabled);
  assert.equal(calls.find(call => call.path === "/api/threads/hunk").input.revision, "review-1");
  await review.getByRole("button", { name: "AI review", exact: true }).click();
  await review.getByText("Check the error path", { exact: true }).waitFor();
  await page.screenshot({ path: "/tmp/citropy-task-review-desktop.png", animations: "disabled" });
  await page.setViewportSize({ width: 600, height: 800 });
  const bounds = await review.boundingBox();
  assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 600 && bounds.y >= 0 && bounds.y + bounds.height <= 800, JSON.stringify(bounds));
  assert.ok(await review.evaluate(node => node.scrollWidth <= node.clientWidth + 1));
  await page.screenshot({ path: "/tmp/citropy-task-review-narrow.png", animations: "disabled" });
  await review.getByRole("button", { name: "Comment on line 2", exact: true }).last().click();
  const feedback = review.getByRole("textbox");
  await feedback.fill("Handle rejection in the caller.");
  await review.getByRole("button", { name: "Send feedback", exact: true }).click();
  await review.waitFor({ state: "hidden" });
  assert.ok(calls.some(call => call.t === "thread.send" && call.text.includes("src/request.ts:2 (new)") && call.text.includes("Handle rejection")));
  if (await page.getByRole("button", { name: "Close navigation", exact: true }).isVisible()) await page.getByRole("button", { name: "Close navigation", exact: true }).click();
  assert.equal(await page.getByRole("button", { name: "Workflows", exact: true }).count(), 0);
  await page.getByPlaceholder("Ask a question or describe a change…").fill("@[src/request.ts]#L1-L2");
  await page.locator(".context-usage button").first().hover();
  await page.getByRole("button", { name: "Inspect context sources", exact: true }).click();
  const context = page.getByRole("dialog", { name: "Context sources", exact: true });
  await context.getByText("/example/AGENTS.md", { exact: true }).waitFor();
  assert.ok(await context.evaluate(node => node.scrollWidth <= node.clientWidth + 1));
  await page.screenshot({ path: "/tmp/citropy-context-narrow.png", animations: "disabled" });
  await context.getByRole("button", { name: "Close", exact: true }).click();
  await page.setViewportSize({ width: 1440, height: 960 });
  assert.equal(await page.getByRole("button", { name: "Workflows", exact: true }).count(), 0);
  await page.screenshot({ path: "/tmp/citropy-composer-clean-desktop.png", animations: "disabled" });
  await page.setViewportSize({ width: 600, height: 800 });
  await page.screenshot({ path: "/tmp/citropy-composer-clean-narrow.png", animations: "disabled" });
  assert.deepEqual(errors, []);
});
