import assert from "node:assert/strict";
import { test } from "node:test";
import { createServer } from "vite";
import react from "@vitejs/plugin-react";
import { chromium } from "playwright";
import { fileURLToPath } from "node:url";

test("new conversations can use an account when the default CLI is unavailable", { timeout: 60000 }, async t => {
  const source = `import React from "react";
import { createRoot } from "react-dom/client";
import { NewConversation } from "/web/src/components/NewConversation.tsx";
import { useApp } from "/web/src/lib/store.ts";
import "/web/src/styles/tokens.css";
import "/web/src/styles/base.css";
import "/web/src/styles/app.css";
import "/web/src/styles/features.css";
import "/web/src/styles/overlays.css";
useApp.setState({ connected: true, newThreadProvider: "pi", activeProjectId: "project", projects: [{ id: "project", name: "Project", path: "/tmp/project", isGit: false, lastOpened: 1 }], providers: [{ id: "pi", label: "Pi", available: false, enabled: true, models: [], supportsPermissionPrompt: true, instances: [{ id: "pvi-personal", name: "Personal", available: true, models: [{ id: "test/account", label: "Account model" }] }] }] });
createRoot(document.getElementById("root")).render(<NewConversation />);`;
  const server = await createServer({ configFile: false, root: fileURLToPath(new URL("..", import.meta.url)), plugins: [react(), { name: "conversation-account-fixture", resolveId(id) { if (id === "/__conversation_fixture.tsx") return id; }, load(id) { if (id === "/__conversation_fixture.tsx") return source; } }], logLevel: "error", server: { host: "127.0.0.1", port: 0, watch: null } });
  await server.listen();
  const browser = await chromium.launch({ headless: true });
  t.after(async () => { await browser.close(); await server.close(); });
  const page = await browser.newPage({ viewport: { width: 900, height: 800 }, reducedMotion: "reduce" });
  const errors = [];
  let created;
  page.on("pageerror", error => errors.push(error.message));
  await page.route("**/api/workspaces?projectId=project", route => route.fulfill({ contentType: "application/json", body: JSON.stringify({ hasCommits: false, branches: [] }) }));
  await page.route("**/api/threads", async route => {
    created = JSON.parse(route.request().postData());
    await route.fulfill({ contentType: "application/json", body: JSON.stringify({ id: "thread", projectId: "project", provider: "pi", providerInstanceId: created.providerInstanceId, model: created.model, title: "New thread", createdAt: 1, updatedAt: 1, status: "idle", usage: {}, permissionMode: "manual", running: false }) });
  });
  const html = '<!doctype html><html data-theme="dark"><body><div id="root"></div><script type="module" src="/__conversation_fixture.tsx"></script></body></html>';
  await page.route("**/conversation-fixture", async route => route.fulfill({ contentType: "text/html", body: await server.transformIndexHtml("/conversation-fixture", html) }));
  await page.goto(new URL("conversation-fixture", server.resolvedUrls.local[0]).href);
  await page.getByRole("combobox", { name: "Account" }).waitFor();
  assert.equal(await page.getByRole("combobox", { name: "Account" }).inputValue(), "pvi-personal");
  await page.getByRole("button", { name: "Create conversation" }).click();
  assert.equal(created.providerInstanceId, "pvi-personal");
  assert.equal(created.model, "test/account");
  assert.deepEqual(errors, []);
});
