import assert from "node:assert/strict";
import { test } from "node:test";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { chromium } from "playwright";
import { appServer } from "./app-server.mjs";

test("question choices, custom answers, drafts, reconnect and skip work at desktop and narrow widths", { timeout: 120000 }, async t => {
  const directory = await mkdtemp(join(tmpdir(), "citropy-questions-ui-"));
  const server = await appServer();
  const browser = await chromium.launch({ headless: true });
  t.after(async () => { await browser.close(); await server.close(); await rm(directory, { recursive: true, force: true }); });
  const page = await browser.newPage({ viewport: { width: 1440, height: 960 }, reducedMotion: "reduce" });
  page.setDefaultTimeout(20000);
  const errors = [];
  const calls = [];
  let fail = false;
  let socket;
  page.on("pageerror", error => errors.push(error.message));
  const questions = [{ id: "scope", question: "How should the world start?", options: [{ label: "Single player", description: "Build the core experience first." }, { label: "Multiplayer", description: "Let friends join from the beginning." }], multiple: false }, { id: "features", question: "Which features should I focus on?", options: [{ label: "Building" }, { label: "Exploring" }], multiple: true }];
  const request = { id: "request", threadId: "chat", messageId: "answer", questions, createdAt: 1 };
  const thread = { id: "chat", projectId: "project", provider: "opencode", model: "example", title: "Build a small world", createdAt: 1, updatedAt: 1, running: true, status: "awaiting", permissionMode: "bypass", usage: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, costUsd: 0, contextTokens: 0, contextMax: 200000, turns: 1 } };
  const project = { id: "project", name: "World builder", path: "/example", isGit: false, lastOpened: 1 };
  const messages = [{ id: "prompt", role: "user", ts: 1, parts: [{ id: "user-text", kind: "text", text: "Help me build a small game." }] }, { id: "answer", role: "assistant", ts: 2, parts: [{ id: "question-tool", kind: "tool", name: "question", shape: "generic", headline: "question", status: "running", input: { questions } }, { id: request.id, kind: "question", questions, status: "pending" }] }];
  const snapshot = { projects: [project], threads: [thread, { ...thread, id: "other", title: "Another task", running: false, status: "idle" }], home: "/example", providers: [{ id: "opencode", label: "OpenCode", available: true, enabled: true, models: [{ id: "example", label: "Muse Spark 1.3 Free" }] }], questions: [request], permissions: [], assistance: { automaticTitles: false, commitModel: null, titleModel: null, reviewModel: null } };
  await page.addInitScript(() => { for (const [key, value] of Object.entries({ project: "project", thread: "chat", inspector: "0", theme: "dark", uiScale: "100" })) localStorage.setItem(`citropy.${key}`, value); });
  await page.routeWebSocket("**/socket*", connection => {
    socket = connection;
    connection.onMessage(raw => {
      const event = JSON.parse(raw); calls.push(event);
      if (event.t === "thread.load") connection.send(JSON.stringify({ t: "thread.messages", threadId: event.id, messages: event.id === "chat" ? messages : [] }));
    });
    connection.send(JSON.stringify({ t: "hello", snapshot }));
  });
  await page.route("**/api/**", async route => {
    const url = new URL(route.request().url());
    if (["/api/skills", "/api/commands"].includes(url.pathname)) return route.fulfill({ json: [] });
    if (url.pathname === "/api/threads/question") {
      const input = route.request().postDataJSON(); calls.push({ path: url.pathname, input });
      if (fail) return route.fulfill({ status: 500, json: { error: "Could not send. Try again." } });
      socket.send(JSON.stringify({ t: "part.patch", threadId: "chat", messageId: "answer", partId: request.id, patch: { status: input.answers ? "answered" : "dismissed", answers: input.answers ?? undefined } }));
      socket.send(JSON.stringify({ t: "question.close", id: request.id }));
      return route.fulfill({ json: { ok: true } });
    }
    return route.fulfill({ status: 404, json: { error: "Fixture route unavailable" } });
  });
  await page.goto(server.url);
  const panel = page.getByRole("region", { name: "Your input", exact: true });
  await panel.waitFor();
  assert.equal(await page.getByText("Running question", { exact: true }).count(), 0);
  assert.equal(await page.locator(".working").count(), 0);
  assert.equal(await panel.getByRole("radio", { checked: true }).count(), 0);
  assert.equal(await panel.getByRole("button", { name: "Next", exact: true }).isDisabled(), true);
  await panel.getByText("Build the core experience first.").click();
  assert.equal(await panel.getByRole("radio", { name: /Single player/ }).isChecked(), true);
  await page.screenshot({ path: "/tmp/citropy-questions-desktop.png", animations: "disabled" });
  await panel.getByRole("radio", { name: /Single player/ }).focus();
  await page.keyboard.press("ArrowDown");
  assert.equal(await panel.getByRole("radio", { name: /Multiplayer/ }).isChecked(), true);
  await panel.getByRole("button", { name: "Next", exact: true }).click();
  await panel.getByRole("checkbox", { name: "Building", exact: true }).check();
  await panel.getByRole("checkbox", { name: "Exploring", exact: true }).check();
  await panel.getByRole("textbox").fill("Keep it offline for now.");
  await page.evaluate(async () => { const { selectThread } = await import('/web/src/lib/store.ts'); selectThread('other'); });
  await panel.waitFor({ state: "hidden" });
  await page.evaluate(async () => { const { selectThread } = await import('/web/src/lib/store.ts'); selectThread('chat'); });
  await panel.waitFor();
  assert.equal(await panel.getByRole("textbox").inputValue(), "Keep it offline for now.");
  socket.close();
  await page.waitForFunction(() => document.querySelector(".question-footer button[type=submit]")?.disabled);
  await page.waitForFunction(() => document.querySelector(".question-footer button[type=submit]")?.disabled === false);
  assert.equal(await panel.getByRole("checkbox", { name: "Building", exact: true }).isChecked(), true);
  await page.setViewportSize({ width: 600, height: 800 });
  if (await page.getByRole("button", { name: "Close navigation", exact: true }).isVisible()) await page.getByRole("button", { name: "Close navigation", exact: true }).click();
  const bounds = await panel.boundingBox();
  assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 600 && bounds.y >= 0 && bounds.y + bounds.height <= 800, JSON.stringify(bounds));
  assert.ok(await panel.evaluate(node => node.scrollWidth <= node.clientWidth + 1));
  await page.screenshot({ path: "/tmp/citropy-questions-narrow.png", animations: "disabled" });
  fail = true;
  await panel.getByRole("button", { name: "Send answers", exact: true }).click();
  await panel.getByRole("alert").waitFor();
  assert.equal(await panel.getByRole("textbox").inputValue(), "Keep it offline for now.");
  fail = false;
  await panel.getByRole("button", { name: "Back", exact: true }).click();
  await panel.getByRole("textbox").fill("A tiny co-op prototype.");
  assert.equal(await panel.getByRole("radio", { checked: true }).count(), 0);
  await panel.getByRole("button", { name: "Next", exact: true }).click();
  await panel.getByRole("button", { name: "Send answers", exact: true }).click();
  await panel.waitFor({ state: "hidden" });
  assert.deepEqual(calls.filter(call => call.path === "/api/threads/question").at(-1).input.answers, { scope: ["A tiny co-op prototype."], features: ["Building", "Exploring", "Keep it offline for now."] });
  assert.equal(calls.some(call => call.t === "thread.send"), false);
  await page.getByRole("button", { name: "Work details", exact: true }).click();
  await page.getByText("Answers shared", { exact: true }).click();
  await page.getByText("A tiny co-op prototype.", { exact: true }).waitFor();
  socket.send(JSON.stringify({ t: "question.request", request }));
  await panel.waitFor();
  assert.equal(await panel.getByRole("radio", { checked: true }).count(), 0);
  await panel.getByRole("button", { name: "Skip", exact: true }).click();
  await panel.waitFor({ state: "hidden" });
  assert.equal(calls.filter(call => call.path === "/api/threads/question").at(-1).input.answers, null);
  assert.deepEqual(errors, []);
});
