import assert from "node:assert/strict";
import { test } from "node:test";
import { createServer, request } from "node:http";
import { mkdtemp, writeFile, readFile, rm, stat, mkdir, cp } from "node:fs/promises";
import { tmpdir, userInfo } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { execFile, spawn } from "node:child_process";
import { promisify } from "node:util";
import { once } from "node:events";
import { WebSocket, WebSocketServer } from "ws";
import { SshEnvironments, shellQuote, sshArguments, sshHosts, validateConnection } from "../desktop/ssh.mjs";
import { remoteProxy } from "../desktop/remote-proxy.mjs";

const run = promisify(execFile);
const root = fileURLToPath(new URL("..", import.meta.url));
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
const listen = server => new Promise(resolve => server.listen(0, "127.0.0.1", () => resolve(server.address().port)));

test("SSH configuration rejects command injection and persists only connection details", async t => {
  const directory = await mkdtemp(join(tmpdir(), "citropy-ssh-config-"));
  t.after(() => rm(directory, { recursive: true, force: true }));
  for (const target of ["-oProxyCommand=touch /tmp/no", "host;pwd", "a@host\nwhoami", "a@$(pwd)", "a@host/path"])
    assert.throws(() => validateConnection({ name: "Test", target }));
  for (const port of [0.5, -1, 65536, "bad"]) assert.throws(() => validateConnection({ name: "Test", target: "host", port }));
  assert.throws(() => validateConnection({ name: "Test", target: "host", node: "node --eval code" }));
  assert.equal(validateConnection({ name: "Test", target: "user@[::1]" }).target, "user@[::1]");
  assert.ok(sshArguments({ port: 22 }).includes("StrictHostKeyChecking=yes"));
  assert.ok(!sshArguments({ port: 0 }).includes("-p"));
  assert.deepEqual(sshArguments({ port: 22 }).slice(-2), ["-p", "22"]);
  assert.deepEqual(sshArguments({ port: 2200 }).slice(-2), ["-p", "2200"]);
  const text = "a 'quoted' $(command) `command`\nfile";
  assert.equal((await run("sh", ["-c", `printf %s ${shellQuote(text)}`])).stdout, text);
  const config = join(directory, "config");
  await writeFile(config, "Host one two\n HostName private\nHost * !no prod-*\nHost one\n");
  assert.deepEqual(await sshHosts(config), ["one", "two"]);
  const manager = new SshEnvironments({ directory, appRoot: root, origin: "http://127.0.0.1:4177" });
  await manager.load();
  const saved = await manager.save({ name: "Development", target: "host", port: 22 });
  await assert.rejects(manager.save({ name: "Duplicate", target: "host", port: 22 }), /already saved/);
  const another = new SshEnvironments({ directory, appRoot: root, origin: manager.origin });
  await another.load();
  assert.deepEqual(another.connections, [saved]);
  assert.equal((await stat(join(directory, "ssh.json"))).mode & 0o777, 0o600);
  assert.ok(!JSON.stringify(another.state()).includes("token"));
  another.sessions.set(saved.id, { status: "connected", proxy: { endpoint: "http://127.0.0.1:49121" } });
  assert.equal(another.state().activeId, "local");
  assert.equal(another.state().connections[0].endpoint, "http://127.0.0.1:49121");
  another.sessions.get(saved.id).status = "disconnected";
  assert.equal(another.state().connections[0].endpoint, undefined);
  another.sessions.delete(saved.id);
  await another.remove(saved.id);
  assert.deepEqual(another.state().connections, []);
});

test("the remote proxy authenticates HTTP and WebSocket requests and never falls back locally", async t => {
  const token = "secret".repeat(12);
  const pending = Promise.withResolvers();
  const server = createServer((req, res) => {
    assert.equal(req.headers["x-citropy-remote-token"], token);
    assert.equal(req.headers.origin, `http://127.0.0.1:${port}`);
    assert.equal(req.headers.cookie, undefined);
    if (req.url === "/api/slow") { pending.resolve(res); return; }
    res.writeHead(200, { "content-type": "application/json" }).end(JSON.stringify({ remote: true, method: req.method }));
  });
  const port = await listen(server);
  const wss = new WebSocketServer({ server, verifyClient: ({ req }) => req.headers["x-citropy-remote-token"] === token });
  const urls = [];
  wss.on("connection", (socket, req) => { urls.push(req.url); socket.on("message", data => socket.send(data)); });
  const origin = "http://127.0.0.1:4177";
  const proxy = await remoteProxy(origin);
  t.after(async () => {
    await proxy.close();
    for (const client of wss.clients) client.terminate();
    wss.close();
    server.closeAllConnections();
    server.close();
  });
  proxy.setTarget({ port, remotePort: port, token });
  const response = await fetch(`${proxy.endpoint}/api/example`, { headers: { origin, cookie: "local-secret=true" } });
  assert.equal(response.headers.get("access-control-allow-origin"), origin);
  assert.deepEqual(await response.json(), { remote: true, method: "GET" });
  assert.equal((await fetch(`${proxy.endpoint}/api/example`, { method: "OPTIONS", headers: { origin, "access-control-request-method": "PATCH" } })).status, 204);
  assert.equal((await fetch(`${proxy.endpoint}/api/example`, { headers: { origin: "https://evil.invalid" } })).status, 403);
  assert.equal(await new Promise(resolve => { const req = request(`${proxy.endpoint}/api/example`, { headers: { host: "evil.invalid" } }, response => { response.resume(); resolve(response.statusCode); }); req.end(); }), 403);
  assert.equal((await fetch(`${proxy.endpoint}/api/example`, { headers: { origin, "sec-fetch-site": "cross-site" } })).status, 200);
  assert.equal((await fetch(`${proxy.endpoint}/api/example`, { headers: { "sec-fetch-site": "cross-site", referer: "https://evil.invalid" } })).status, 403);
  assert.equal((await fetch(`${proxy.endpoint}/api/example`, { headers: { "sec-fetch-site": "cross-site", referer: origin } })).status, 200);
  assert.equal((await fetch(`${proxy.endpoint}/api/remote/shutdown`, { method: "POST", headers: { origin } })).status, 404);
  assert.equal((await fetch(`${proxy.endpoint}/mcp/task`, { headers: { origin } })).status, 404);
  const socket = new WebSocket(proxy.endpoint.replace("http", "ws") + "/socket", { origin });
  await once(socket, "open");
  socket.send("remote output");
  assert.equal(String((await once(socket, "message"))[0]), "remote output");
  const workspace = new WebSocket(proxy.endpoint.replace("http", "ws") + "/socket?workspace=1", { origin });
  await once(workspace, "open");
  workspace.send("workspace update");
  assert.equal(String((await once(workspace, "message"))[0]), "workspace update");
  assert.equal(urls.at(-1), "/socket?workspace=1");
  workspace.close();
  const closed = once(socket, "close");
  proxy.setTarget(undefined);
  await closed;
  assert.equal((await fetch(`${proxy.endpoint}/api/example`, { headers: { origin } })).status, 503);
  proxy.setTarget({ port, remotePort: port, token });
  assert.equal((await fetch(`${proxy.endpoint}/api/example`, { headers: { origin } })).status, 200);
  for (let attempt = 0; attempt < 20; attempt++) {
    const connected = await fetch(`${proxy.endpoint}/api/example`, { headers: { origin } });
    await connected.json();
    proxy.setTarget(undefined);
    const disconnected = await fetch(`${proxy.endpoint}/api/example`, { headers: { origin } });
    assert.equal(disconnected.status, 503);
    await disconnected.json();
    proxy.setTarget({ port, remotePort: port, token });
  }
  const slow = fetch(`${proxy.endpoint}/api/slow`, { headers: { origin } });
  const delayed = await pending.promise;
  proxy.setTarget(undefined);
  const cancelled = await slow;
  assert.equal(cancelled.status, 503);
  assert.match((await cancelled.json()).error, /connection changed/);
  delayed.end("old host response");
  proxy.setTarget({ port, remotePort: port, token });
  assert.equal((await fetch(`${proxy.endpoint}/api/example`, { headers: { origin } })).status, 200);
});

test("packaged SSH uploads use the retained dependency lockfile", async t => {
  const directory = await mkdtemp(join(tmpdir(), "citropy-ssh-packaged-"));
  t.after(() => rm(directory, { recursive: true, force: true }));
  for (const name of ["server", "shared", "skills", "desktop"]) await mkdir(join(directory, name));
  await writeFile(join(directory, "package.json"), '{"name":"packaged-fixture"}');
  const lock = '{"lockfileVersion":3,"packages":{}}';
  await writeFile(join(directory, "desktop/remote-package-lock.json"), lock);
  await cp(join(root, "desktop/ssh-bootstrap.mjs"), join(directory, "desktop/ssh-bootstrap.mjs"));
  const manager = new SshEnvironments({ directory, appRoot: directory, origin: "http://127.0.0.1:4177" });
  const bundle = await manager.bundle(new AbortController().signal);
  const uploaded = await manager.command("tar", ["-xOzf", "-", "./package-lock.json"], { input: bundle.archive });
  assert.equal(uploaded, lock);
});

test("shared defaults serialize updates and disconnect a host that cannot apply them", async t => {
  const directory = await mkdtemp(join(tmpdir(), "citropy-shared-defaults-"));
  const received = Promise.withResolvers();
  const release = Promise.withResolvers();
  let defaults = {};
  let remoteDefaults = {};
  let fail = false;
  const server = createServer(async (req, res) => {
    let body = "";
    for await (const chunk of req) body += chunk;
    const { settings } = JSON.parse(body);
    if (fail) { res.writeHead(503, { "content-type": "application/json" }).end('{"error":"Backend unavailable"}'); return; }
    if (settings.permissionMode === "plan") { received.resolve(); await release.promise; }
    remoteDefaults = settings;
    res.writeHead(200, { "content-type": "application/json" }).end(JSON.stringify(settings));
  });
  const port = await listen(server);
  const proxy = await remoteProxy("http://127.0.0.1:4177");
  proxy.setTarget({ port, remotePort: port, token: "fixture" });
  const manager = new SshEnvironments({ directory, appRoot: root, origin: "http://127.0.0.1:4177", projectDefaults: async settings => {
    if (settings !== undefined) defaults = settings;
    return defaults;
  } });
  t.after(async () => {
    release.resolve();
    await manager.dispose();
    server.closeAllConnections();
    await new Promise(resolve => server.close(resolve));
    await rm(directory, { recursive: true, force: true });
  });
  const connection = await manager.save({ name: "Shared host", target: "fixture" });
  manager.sessions.set(connection.id, { status: "connected", proxy });
  const first = manager.syncProjectDefaults({ permissionMode: "plan" });
  await received.promise;
  const second = manager.syncProjectDefaults({ permissionMode: "manual" });
  const controller = new AbortController();
  const cancelled = manager.syncProjectDefaults(undefined, manager.sessions.get(connection.id), controller.signal);
  const cancellation = assert.rejects(cancelled, { name: "AbortError" });
  controller.abort();
  assert.equal(defaults.permissionMode, "plan");
  release.resolve();
  await Promise.all([first, second]);
  await cancellation;
  assert.equal(manager.state().connections[0].status, "connected");
  assert.equal(defaults.permissionMode, "manual");
  assert.deepEqual(remoteDefaults, defaults);
  fail = true;
  await assert.rejects(manager.syncProjectDefaults({ permissionMode: "acceptEdits" }), /saved locally.*Shared host: Backend unavailable/);
  assert.equal(defaults.permissionMode, "acceptEdits");
  assert.equal(manager.state().connections[0].status, "error");
  assert.equal((await fetch(`${proxy.endpoint}/api/projects/defaults`)).status, 503);
});

test("real SSH launch, remote tasks, disconnect, reconnect, and cleanup", { timeout: 180000 }, async t => {
  const directory = await mkdtemp(join(tmpdir(), "citropy-ssh-live-"));
  const home = join(directory, "remote-home");
  const bin = join(directory, "bin");
  await mkdir(home);
  await mkdir(bin);
  const previousPath = process.env.PATH;
  let daemon;
  let manager;
  let remote;
  let socket;
  t.after(async () => {
    socket?.terminate();
    await manager?.dispose();
    if (remote) {
      await fetch(`http://127.0.0.1:${remote.port}/api/remote/shutdown`, { method: "POST", headers: { "x-citropy-remote-token": remote.token } }).catch(() => {});
      try { process.kill(remote.pid, "SIGTERM"); } catch {}
    }
    daemon?.kill();
    process.env.PATH = previousPath;
    await rm(directory, { recursive: true, force: true });
  });
  await run("ssh-keygen", ["-q", "-t", "ed25519", "-N", "", "-f", join(directory, "host")]);
  await run("ssh-keygen", ["-q", "-t", "ed25519", "-N", "", "-f", join(directory, "client")]);
  const probe = createServer();
  const port = await listen(probe);
  await new Promise(resolve => probe.close(resolve));
  const command = join(directory, "remote-command");
  await writeFile(command, `#!/bin/sh\nexport HOME=${shellQuote(home)}\nexport PATH=/usr/bin:/bin\nexport SHELL=/bin/bash\nexec /bin/sh -c "$SSH_ORIGINAL_COMMAND"\n`, { mode: 0o700 });
  const config = join(directory, "sshd_config");
  await writeFile(config, `ListenAddress 127.0.0.1\nPort ${port}\nHostKey ${directory}/host\nPidFile ${directory}/pid\nAuthorizedKeysFile ${directory}/client.pub\nStrictModes no\nUsePAM no\nPasswordAuthentication no\nKbdInteractiveAuthentication no\nAllowUsers ${userInfo().username}\nAllowTcpForwarding yes\nForceCommand ${command}\n`);
  daemon = spawn("/usr/sbin/sshd", ["-D", "-e", "-f", config], { stdio: ["ignore", "ignore", "pipe"] });
  let daemonOutput = "";
  daemon.stderr.on("data", chunk => { daemonOutput += chunk; });
  await pause(250);
  assert.equal(daemon.exitCode, null, daemonOutput);
  const hostKey = (await readFile(join(directory, "host.pub"), "utf8")).trim();
  await writeFile(join(directory, "known_hosts"), `[127.0.0.1]:${port} ${hostKey}\n`);
  const sshConfig = join(directory, "ssh_config");
  await writeFile(sshConfig, `Host *\n IdentityFile ${directory}/client\n IdentitiesOnly yes\n UserKnownHostsFile ${directory}/known_hosts\n`);
  await writeFile(join(bin, "ssh"), `#!/bin/sh\nexec /usr/bin/ssh -F ${shellQuote(sshConfig)} "$@"\n`, { mode: 0o700 });
  process.env.PATH = `${bin}:${previousPath}`;
  const fixture = join(directory, "app");
  await mkdir(fixture);
  for (const path of ["server", "shared", "skills", "desktop"]) await cp(join(root, path), join(fixture, path), { recursive: true });
  const install = `require('node:fs').symlinkSync(${JSON.stringify(join(root, "node_modules"))},'node_modules','dir')`;
  const manifest = { name: "citropy-ssh-test", version: "1.0.0", type: "module", scripts: { postinstall: `${shellQuote(process.execPath)} -e ${shellQuote(install)}` } };
  await writeFile(join(fixture, "package.json"), JSON.stringify(manifest));
  await writeFile(join(fixture, "package-lock.json"), JSON.stringify({ name: manifest.name, version: manifest.version, lockfileVersion: 3, packages: { "": { name: manifest.name, version: manifest.version, hasInstallScript: true } } }));
  const events = [];
  let defaults = { provider: "claude", model: "only-on-local", effort: "high", permissionMode: "plan", browserAccess: false };
  manager = new SshEnvironments({ directory: join(directory, "client-state"), appRoot: fixture, origin: "http://127.0.0.1:4177", projectDefaults: async settings => {
    if (settings !== undefined) defaults = settings;
    return defaults;
  }, changed: state => events.push(state) });
  await manager.load();
  const connection = await manager.save({ name: "SSH test", target: `${userInfo().username}@127.0.0.1`, port, node: process.execPath });
  const connected = await manager.connect(connection.id);
  assert.equal(connected.activeId, connection.id);
  assert.equal(connected.connections[0].status, "connected");
  assert.ok(events.some(state => state.connections[0]?.message === "Installing remote backend…"));
  remote = JSON.parse(await readFile(join(home, ".citropy/ssh", connection.id, "server.json"), "utf8"));
  assert.equal((await fetch(`http://127.0.0.1:${remote.port}/api/health`)).status, 401);
  assert.equal((await fetch(`http://127.0.0.1:${remote.port}/api/health`, { headers: { "x-citropy-remote-token": "incorrect" } })).status, 401);
  const headers = { origin: manager.origin };
  assert.deepEqual(await fetch(`${connected.endpoint}/api/projects/defaults`, { headers }).then(response => response.json()), defaults);
  const health = await fetch(`${connected.endpoint}/api/health`, { headers }).then(response => response.json());
  assert.equal(health.environmentId, connection.id);
  await mkdir(join(home, "project"));
  await run("git", ["init", "--initial-branch=ssh-fixture", join(home, "project")]);
  await writeFile(join(home, "project/remote.txt"), "Remote fixture contents");
  socket = new WebSocket(connected.endpoint.replace("http", "ws") + "/socket", { origin: manager.origin });
  const messages = [];
  socket.on("message", raw => messages.push(JSON.parse(String(raw))));
  await once(socket, "open");
  const until = async predicate => {
    for (let attempt = 0; attempt < 100 && !predicate(); attempt++) await pause(50);
    assert.ok(predicate(), JSON.stringify(messages.filter(message => message.t !== "hello")));
  };
  await until(() => messages.some(message => message.t === "hello"));
  const hello = messages.find(message => message.t === "hello");
  assert.equal(hello.snapshot.home, home);
  assert.deepEqual(hello.snapshot.projectDefaults, defaults);
  assert.ok(hello.snapshot.tools.every(tool => !/^(browser_|computer_)/.test(tool.name)));
  assert.ok(hello.snapshot.tools.some(tool => tool.name === "subagent_providers"));
  assert.ok(hello.snapshot.tools.some(tool => tool.name === "subagent_start"));
  socket.send(JSON.stringify({ t: "project.choose", path: join(home, "project") }));
  await until(() => messages.some(message => message.t === "project.chosen"));
  const projectId = messages.find(message => message.t === "project.chosen").projectId;
  assert.ok(projectId);
  const overrides = { permissionMode: "manual", browserAccess: true };
  assert.equal((await fetch(`${connected.endpoint}/api/projects?projectId=${projectId}`, { method: "PATCH", headers: { ...headers, "content-type": "application/json" }, body: JSON.stringify({ settings: overrides }) })).status, 200);
  const originalTunnel = manager.sessions.get(connection.id).child;
  await manager.local();
  await manager.syncProjectDefaults({ ...defaults, permissionMode: "acceptEdits" });
  assert.deepEqual(await fetch(`${connected.endpoint}/api/projects/defaults`, { headers }).then(response => response.json()), defaults);
  defaults = { ...defaults, autoPull: true };
  await manager.connect(connection.id);
  assert.equal(manager.sessions.get(connection.id).child, originalTunnel);
  assert.deepEqual(await fetch(`${connected.endpoint}/api/projects/defaults`, { headers }).then(response => response.json()), defaults);
  await until(() => messages.some(message => message.t === "git.status" && message.status.branch === "ssh-fixture"));
  socket.send(JSON.stringify({ t: "file.read", requestId: "remote-read", projectId, path: "remote.txt" }));
  await until(() => messages.some(message => message.t === "file.content" && message.content === "Remote fixture contents"));
  socket.send(JSON.stringify({ t: "panel.open", id: "ssh-terminal", projectId, kind: "terminal" }));
  await until(() => messages.some(message => message.t === "panel.upsert"));
  socket.send(JSON.stringify({ t: "term.open", termId: "ssh-terminal", projectId, cols: 80, rows: 24 }));
  await until(() => messages.some(message => message.t === "term.data"));
  socket.send(JSON.stringify({ t: "term.data", termId: "ssh-terminal", data: "printf 'remote-shell-marker\\n'\r" }));
  await until(() => messages.some(message => message.t === "term.data" && message.data.includes("remote-shell-marker")));
  const authHeaders = { "x-citropy-remote-token": remote.token };
  assert.equal((await fetch(`http://127.0.0.1:${remote.port}/api/health`, { headers: authHeaders })).status, 200);
  const failedConnection = await manager.save({ name: "Rejected", target: "citropy-missing-test-user@127.0.0.1", port, node: process.execPath });
  await assert.rejects(manager.connect(failedConnection.id), /Permission denied/);
  assert.equal(manager.activeId, connection.id);
  assert.equal((await fetch(`${connected.endpoint}/api/health`, { headers })).status, 200);
  await manager.remove(failedConnection.id);
  const endpoint = connected.endpoint;
  await manager.disconnect(connection.id);
  assert.equal(manager.activeId, connection.id);
  assert.equal((await fetch(`${endpoint}/api/health`, { headers })).status, 503);
  process.kill(remote.pid, 0);
  await writeFile(join(fixture, "shared/ssh-fixture.ts"), "export {};\n");
  const reconnected = await manager.connect(connection.id);
  assert.equal(reconnected.endpoint, endpoint);
  assert.equal(reconnected.connections[0].message, undefined);
  const previousPid = remote.pid;
  remote = JSON.parse(await readFile(join(home, ".citropy/ssh", connection.id, "server.json"), "utf8"));
  assert.notEqual(remote.pid, previousPid);
  socket = new WebSocket(endpoint.replace("http", "ws") + "/socket", { origin: manager.origin });
  const recovered = once(socket, "message");
  await once(socket, "open");
  const snapshot = JSON.parse(String((await recovered)[0])).snapshot;
  assert.ok(snapshot.projects.some(project => project.id === projectId));
  assert.deepEqual(snapshot.projectDefaults, defaults);
  assert.deepEqual(snapshot.projects.find(project => project.id === projectId).settings, overrides);
  assert.ok(snapshot.shells.some(shell => shell.panelId === "ssh-terminal" && shell.status === "running"));
  socket.send(JSON.stringify({ t: "term.close", termId: "ssh-terminal" }));
  await pause(250);
  await manager.disconnect(connection.id);
  const oldPid = remote.pid;
  const updated = await manager.connect(connection.id);
  remote = JSON.parse(await readFile(join(home, ".citropy/ssh", connection.id, "server.json"), "utf8"));
  assert.equal(remote.pid, oldPid);
  assert.equal(updated.connections[0].message, undefined);
  const tunnel = manager.sessions.get(connection.id).child;
  const dropped = once(tunnel, "exit");
  tunnel.kill("SIGKILL");
  await dropped;
  assert.equal(manager.state().connections[0].status, "error");
  await manager.local();
  assert.equal(manager.state().activeId, "local");
  const pending = manager.connect(connection.id).then(() => null, error => error);
  await manager.disconnect(connection.id);
  assert.ok(await pending);
  assert.equal(manager.state().activeId, "local");
  assert.equal(manager.sessions.get(connection.id).child, undefined);
  await manager.remove(connection.id);
  assert.equal(manager.state().connections.length, 0);
  process.kill(remote.pid, 0);
});
