import assert from "node:assert/strict";
import { test } from "node:test";
import { EventEmitter } from "node:events";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const directory = mkdtempSync(join(tmpdir(), "citropy-workspace-feed-"));
process.env.CITROPY_DATA_DIR = directory;
const { attachWorkspaceFeed } = await import("../server/workspace-feed.ts");
const { store } = await import("../server/store.ts");
const { bus } = await import("../server/bus.ts");
const { eventJournal } = await import("../server/event-journal.ts");
test.after(() => { eventJournal.close(); rmSync(directory, { recursive: true, force: true }); });

test("background workspace feed sends only sidebar metadata, coalesces changes and releases subscriptions", async () => {
  const project = store.openProject(directory);
  const thread = store.createThread({ projectId: project.id, provider: "codex", title: "Background task", permissionMode: "full" });
  store.createThread({ projectId: project.id, provider: "codex", title: "Child task", permissionMode: "full", parentThreadId: thread.id });
  const socket = new EventEmitter();
  const events = [];
  const closes = [];
  socket.OPEN = socket.readyState = 1;
  socket.bufferedAmount = 0;
  socket.send = raw => events.push(JSON.parse(raw));
  socket.close = code => { closes.push(code); socket.readyState = 3; socket.emit("close"); };
  attachWorkspaceFeed(socket);
  assert.equal(events[0].t, "workspace.snapshot");
  assert.equal(events[0].snapshot.threads.length, 1);
  assert.equal(events[0].snapshot.projects[0].id, project.id);
  assert.equal(events[0].snapshot.threads[0].usage, undefined);
  assert.equal(events[0].snapshot.threads[0].messages, undefined);
  const meta = store.allMeta().find(entry => entry.id === thread.id);
  for (let index = 0; index < 20; index++) bus.emit({ t: "thread.upsert", thread: { ...meta, updatedAt: index, usage: { ...meta.usage, outputTokens: index } } });
  bus.emit({ t: "term.data", id: "terminal", data: "private output" });
  bus.emit({ t: "shell.output", id: "shell", output: "private output" });
  await new Promise(resolve => setTimeout(resolve, 150));
  assert.equal(events.length, 1);
  bus.emit({ t: "thread.upsert", thread: { ...meta, status: "working", running: true } });
  bus.emit({ t: "thread.upsert", thread: { ...meta, status: "awaiting", running: false } });
  await new Promise(resolve => setTimeout(resolve, 150));
  assert.equal(events.length, 2);
  assert.equal(events[1].t, "workspace.thread");
  assert.equal(events[1].thread.status, "awaiting");
  assert.equal(events[1].sequence, undefined);
  bus.emit({ t: "thread.upsert", thread: { ...meta, status: "working", running: true } });
  bus.emit({ t: "thread.remove", id: thread.id });
  await new Promise(resolve => setTimeout(resolve, 150));
  assert.equal(events.length, 3);
  assert.equal(events.at(-1).t, "thread.remove");
  bus.emit({ t: "project.upsert", project: { ...project, name: "Renamed" } });
  assert.equal(events.at(-1).project.name, "Renamed");
  socket.emit("message", JSON.stringify({ t: "thread.create", projectId: project.id }));
  assert.deepEqual(closes, [1008]);
  const count = events.length;
  bus.emit({ t: "project.remove", id: project.id });
  assert.equal(events.length, count);
});
