import assert from "node:assert/strict";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import { createServer } from "vite";
import react from "@vitejs/plugin-react";
import { chromium } from "playwright";

test("large tool groups keep bounded rows, focus and disclosures", { timeout: 60_000 }, async t => {
  const root = fileURLToPath(new URL("../..", import.meta.url));
  const server = await createServer({ configFile: false, root, cacheDir: `${root}/node_modules/.vite-work-group-tests`, plugins: [react()], logLevel: "error", server: { host: "127.0.0.1", port: 0, watch: null } });
  await server.listen();
  const browser = await chromium.launch();
  t.after(async () => { await browser.close(); await server.close(); });
  const page = await browser.newPage({ viewport: { width: 1280, height: 860 }, reducedMotion: "reduce" });
  page.setDefaultTimeout(10_000);
  const errors = [];
  page.on("pageerror", error => errors.push(error.message));
  const path = "/work-group-fixture.html";
  const html = await server.transformIndexHtml(path, `<!doctype html><html data-theme="neutral" data-scheme="dark"><body style="margin:0;background:#1e1e1e"><div id="fixture" style="position:absolute;inset:20px"></div><script type="module">
    import React from 'react';
    import { createRoot } from 'react-dom/client';
    import { WorkGroup } from '/web/src/components/WorkGroup.tsx';
    import { useApp } from '/web/src/lib/store.ts';
    import '/web/src/styles/tokens.css';
    import '/web/src/styles/base.css';
    import '/web/src/styles/conversation.css';
    import '/web/src/styles/virtual-list.css';
    const tool = index => ({ id: 'p' + index, kind: 'tool', name: 'Read', shape: 'read', headline: 'src/file-' + index + '.ts', status: 'ok', startedAt: 1, endedAt: 2, output: 'Output for tool ' + index });
    const parts = Array.from({ length: 1000 }, (_, index) => tool(index));
    useApp.setState({ parts: new Map(parts.map(part => [part.id, part])), disclosures: { p0: { group: true } } });
    function Fixture() {
      const [ids, setIds] = React.useState(parts.map(part => part.id));
      window.appendTool = () => {
        const part = { ...tool(1000), status: 'running' };
        useApp.setState(state => ({ parts: new Map([...state.parts, [part.id, part]]) }));
        setIds(ids => [...ids, part.id]);
      };
      window.finishTool = () => useApp.setState(state => ({ parts: new Map([...state.parts, ['p1000', { ...state.parts.get('p1000'), status: 'ok', output: 'Finished live tool' }]]) }));
      return React.createElement('div', { className: 'scroll', style: { height: '100%', overflow: 'auto' } }, React.createElement('div', { style: { height: 140 } }), React.createElement(WorkGroup, { ids, live: true }));
    }
    const root = createRoot(document.querySelector('#fixture'));
    root.render(React.createElement(Fixture));
    window.showConversation = async () => {
      const { Conversation } = await import('/web/src/components/Conversation.tsx');
      const messages = Array.from({ length: 60 }, (_, index) => ({ id: 'm' + index, role: 'user', ts: index, partIds: ['text' + index] }));
      const text = messages.map((message, index) => ({ id: 'text' + index, kind: 'text', text: 'Earlier message ' + index, complete: true }));
      messages.push({ id: 'work', role: 'assistant', ts: 61, partIds: parts.map(part => part.id) });
      useApp.setState({ activeThreadId: 'chat', threads: { chat: { id: 'chat', provider: 'claude', title: 'Tools', status: 'idle' } }, loaded: { chat: true }, order: { chat: messages.map(message => message.id) }, messages: Object.fromEntries(messages.map(message => [message.id, message])), parts: new Map([...parts, ...text].map(part => [part.id, part])), disclosures: { p0: { activity: true, group: true } } });
      document.querySelector('#fixture').style.display = 'flex';
      root.render(React.createElement(Conversation));
    };
  </script></body></html>`);
  await page.route(`**${path}`, route => route.fulfill({ contentType: "text/html", body: html }));
  await page.goto(new URL(path, server.resolvedUrls.local[0]).href);
  await page.locator("#tool-p0").waitFor();
  const rows = await page.locator(".work-tree-row").count();
  const descendants = await page.locator(".group-body *").count();
  assert.ok(rows < 50);
  assert.ok(descendants < 1200);
  t.diagnostic(`${rows} mounted rows and ${descendants} descendants for 1000 tools`);
  await page.screenshot({ path: "/tmp/citropy-work-group-desktop.png" });
  await page.locator("#tool-p0 .tool-head").click();
  await page.getByText("Output for tool 0", { exact: true }).waitFor();
  await page.locator(".scroll").evaluate(element => { element.scrollTop = element.scrollHeight; });
  await page.locator("#tool-p999").waitFor();
  assert.equal(await page.evaluate(() => document.activeElement?.closest('.tool')?.id), "tool-p0");
  assert.ok(await page.locator(".work-tree-row").count() < 50);
  await page.locator("#tool-p999 .tool-head").click();
  await page.getByText("Output for tool 999", { exact: true }).waitFor();
  await page.waitForFunction(() => !document.querySelector('#tool-p0'));
  await page.locator(".scroll").evaluate(element => { element.scrollTop = 0; });
  await page.getByText("Output for tool 0", { exact: true }).waitFor();
  await page.locator("#tool-p0 .tool-head").focus();
  await page.evaluate(() => window.appendTool());
  await page.locator(".scroll").evaluate(element => { element.scrollTop = element.scrollHeight; });
  await page.locator("#tool-p1000").waitFor();
  await page.locator("#tool-p1000 .tool-head").click();
  await page.evaluate(() => window.finishTool());
  await page.getByText("Finished live tool", { exact: true }).waitFor();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator(".scroll").evaluate(element => { element.scrollTop = element.scrollHeight; });
  assert.ok(await page.locator(".work-tree-row").count() < 50);
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: "/tmp/citropy-work-group-narrow.png" });
  await page.evaluate(() => window.showConversation());
  await page.locator("#tool-p999").waitFor();
  assert.ok(await page.locator(".work-tree-row").count() < 50);
  assert.ok(await page.locator(".timeline-row").count() < 15);
  await page.locator("#tool-p999 .tool-head").click();
  await page.getByText("Output for tool 999", { exact: true }).waitFor();
  await page.locator(".canvas").hover();
  await page.mouse.wheel(0, -100_000);
  await page.locator(".canvas").evaluate(element => { element.scrollTop = 0; });
  await page.getByText("Earlier message 0", { exact: true }).waitFor();
  await page.locator(".canvas").evaluate(element => { element.scrollTop = element.scrollHeight; });
  await page.getByText("Output for tool 999", { exact: true }).waitFor();
  assert.ok(await page.locator(".work-tree-row").count() < 50);
  assert.deepEqual(errors, []);
});
