export {
  AlertTriangle,
  ArrowUp,
  Ban,
  Brain,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronRight,
  ChevronsUpDown,
  CircleDot,
  Command,
  Copy,
  CornerDownLeft,
  ExternalLink,
  FilePlus2,
  FileText,
  Folder,
  FolderOpen,
  GitBranch,
  GitCommitVertical,
  Globe,
  Layers,
  ListChecks,
  MessageSquarePlus,
  Moon,
  PanelLeft,
  PanelRight,
  Pencil,
  Plus,
  RotateCcw,
  Search,
  ShieldCheck,
  SquarePen,
  Square,
  Sun,
  Terminal,
  Trash2,
  Wrench,
  X,
  Zap,
} from "lucide-react";

import { FilePlus2, FileText, Globe, Layers, ListChecks, Pencil, Search, Terminal, Wrench, Monitor } from "lucide-react";
import type { ToolShape } from "../../../shared/protocol.ts";

export const shapeIcon = {
  command: Terminal,
  read: FileText,
  write: FilePlus2,
  edit: Pencil,
  search: Search,
  web: Globe,
  computer: Monitor,
  task: Layers,
  todo: ListChecks,
  generic: Wrench,
} satisfies Record<ToolShape, typeof Terminal>;
